version: '3.8'
services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - CHATGPT=<Your OpenAI API Key>
      - GOOGLE_API_KEY=<Your Google API Key>
      - CORS_ALLOWED_DOMAINS=["http://localhost","https://localhost","http://localhost:3000","https://localhost:3000"]
      # Set other environment variables as needed
